spring:
  datasource:
      url: jdbc:mysql://localhost:3306/simpleshop
      username: user
      password: user
      testWhileIdle: true
      validationQuery: SELECT 1
  jpa:
      show-sql: false
      hibernate:
                ddl-auto: update
                naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
                hibernate:
                          dialect: org.hibernate.dialect.MySQL5Dialect

app:
  name: Owl Shop
  mail:
        username: null
        password: null
logging:
  level:
    org:
      hibernate: info